In [2]:
#1
import numpy as np 

a=np.array([[0,1,2],[3,4,5],[6,7,8]])
print ("array :",a)
b= a.tolist()
print("list :",b)

array : [[0 1 2]
 [3 4 5]
 [6 7 8]] .
list : [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [3]:
#2
import numpy as np 

a=np.array([[0,1,2],[3,4,5],[6,7,8]])
print (a)
print (a[0,0]+a[1,1]+a[2,2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [1]:
import numpy as np 

a=np.array([[3,1,2],[4,4,5],[6,7,8]])
print (a)
x=int(input("donner un nbre"))
for i in[[3,1,2],[4,4,5],[6,7,8]]:
    for j in i :
        if j>=x : 
            print (j)
        else:
            print ("Eror")
        

[[3 1 2]
 [4 4 5]
 [6 7 8]]
donner un nbre3
3
Eror
Eror
4
4
5
6
7
8


In [1]:
#4
import numpy as np
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
b=np.array([[3,1,2],[4,4,5],[6,7,8]])
c=(a+b)
print (c)

[[ 3  2  4]
 [ 7  8 10]
 [12 14 16]]


In [7]:
import numpy as np
from statistics import mean 
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
b=np.array([[3,1,2],[4,4,5],[6,7,8]])
c= mean(a)
d= mean(b)
e= mean(c)
f=(a-c)
g=(b-d)
print ("le résultat de la première liste",f)
print ("le résultat de la seconde liste",g)

TypeError: can't convert type 'ndarray' to numerator/denominator